# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ceeeb8107976debe9767b2a4e06f3b976e2038d09389138ad521eadb6393a192c269016e6e92f5b7285a80b1da803ca04debc94c77f1a463fcffe7f4d4375025

test:
  secret_key_base: b11da733230e9c52cceb19a71c711a57ef10da9330787df19c0d9623179d7e4f98aedebcacb93c0f7989dcdffb54bee88be5b717719cb11f807db8d6ea95e657

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
